// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type Feed struct {
	ID            string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Name          string
	Url           string
	UserID        string
	LastFetchedAt sql.NullTime
	Description   sql.NullString
	Etag          sql.NullString
	LastModified  sql.NullString
}

type FeedFollow struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    string
	FeedID    string
}

type Post struct {
	ID          string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Url         string
	Description sql.NullString
	PublishedAt time.Time
	FeedID      string
}

type PostRead struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	PostID    string
	UserID    string
}

type PostSafe struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	PostID    string
	UserID    string
}

type User struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}
