// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: posts.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (id, title, url, description, published_at, feed_id)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, created_at, updated_at, title, url, description, published_at, feed_id
`

type CreatePostParams struct {
	ID          string
	Title       string
	Url         string
	Description sql.NullString
	PublishedAt time.Time
	FeedID      string
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.ID,
		arg.Title,
		arg.Url,
		arg.Description,
		arg.PublishedAt,
		arg.FeedID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.PublishedAt,
		&i.FeedID,
	)
	return i, err
}

const getPostsByUser = `-- name: GetPostsByUser :many
SELECT id, created_at, updated_at, title, url, description, published_at, feed_id FROM posts WHERE feed_id IN (SELECT feed_id FROM feed_follows WHERE user_id = ?1) ORDER BY published_at DESC LIMIT ?2
`

type GetPostsByUserParams struct {
	UserID string
	Limit  int64
}

func (q *Queries) GetPostsByUser(ctx context.Context, arg GetPostsByUserParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getPostsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPostsByUser = `-- name: SearchPostsByUser :many
SELECT posts.id as id, title, posts.url as url, posts.description as description, published_at, feeds.name as feed_name, feeds.id as feed_id, post_saves.created_at as saved_at, post_reads.created_at as read_at FROM posts
JOIN feeds ON posts.feed_id = feeds.id
LEFT JOIN post_saves ON posts.id = post_saves.post_id AND post_saves.user_id = ?1
LEFT JOIN post_reads ON posts.id = post_reads.post_id AND post_reads.user_id = ?1
WHERE feed_id IN (SELECT feed_id FROM feed_follows WHERE feed_follows.user_id = ?1) 
AND ( CAST(?2 AS TEXT) = ''
      OR posts.title LIKE '%' || CAST(?2 AS TEXT) || '%'
      OR posts.description LIKE '%' || CAST(?2 AS TEXT) || '%'
    )
AND ( CAST(?3 AS BOOLEAN) = false OR post_reads.id  IS NULL )
AND ( CAST(?4 AS BOOLEAN)  = false OR post_saves.id IS NOT NULL )
ORDER BY published_at DESC LIMIT ?5
`

type SearchPostsByUserParams struct {
	UserID         string
	SearchText     string
	FilterByUnread bool
	FilterBySaved  bool
	LimitCount     int64
}

type SearchPostsByUserRow struct {
	ID          string
	Title       string
	Url         string
	Description sql.NullString
	PublishedAt time.Time
	FeedName    string
	FeedID      string
	SavedAt     sql.NullTime
	ReadAt      sql.NullTime
}

func (q *Queries) SearchPostsByUser(ctx context.Context, arg SearchPostsByUserParams) ([]SearchPostsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, searchPostsByUser,
		arg.UserID,
		arg.SearchText,
		arg.FilterByUnread,
		arg.FilterBySaved,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPostsByUserRow
	for rows.Next() {
		var i SearchPostsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedName,
			&i.FeedID,
			&i.SavedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
