// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: read_posts.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteReadPost = `-- name: DeleteReadPost :exec
DELETE FROM post_reads WHERE user_id = $1 AND post_id = $2
`

type DeleteReadPostParams struct {
	UserID uuid.UUID
	PostID uuid.UUID
}

func (q *Queries) DeleteReadPost(ctx context.Context, arg DeleteReadPostParams) error {
	_, err := q.db.ExecContext(ctx, deleteReadPost, arg.UserID, arg.PostID)
	return err
}

const saveReadPost = `-- name: SaveReadPost :exec
INSERT INTO post_reads (id, post_id, user_id) VALUES ($1, $2, $3)
`

type SaveReadPostParams struct {
	ID     uuid.UUID
	PostID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) SaveReadPost(ctx context.Context, arg SaveReadPostParams) error {
	_, err := q.db.ExecContext(ctx, saveReadPost, arg.ID, arg.PostID, arg.UserID)
	return err
}
