// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: saved_posts.sql

package database

import (
	"context"
)

const deleteSavedPost = `-- name: DeleteSavedPost :exec
DELETE FROM post_saves WHERE post_id = ? AND user_id = ?
`

type DeleteSavedPostParams struct {
	PostID string
	UserID string
}

func (q *Queries) DeleteSavedPost(ctx context.Context, arg DeleteSavedPostParams) error {
	_, err := q.db.ExecContext(ctx, deleteSavedPost, arg.PostID, arg.UserID)
	return err
}

const saveSavedPost = `-- name: SaveSavedPost :exec
INSERT INTO post_saves (id, post_id, user_id) VALUES (?, ?, ?)
`

type SaveSavedPostParams struct {
	ID     string
	PostID string
	UserID string
}

func (q *Queries) SaveSavedPost(ctx context.Context, arg SaveSavedPostParams) error {
	_, err := q.db.ExecContext(ctx, saveSavedPost, arg.ID, arg.PostID, arg.UserID)
	return err
}
