// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: saved_posts.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteSavedPost = `-- name: DeleteSavedPost :exec
DELETE FROM post_saves WHERE post_id = $1 AND user_id = $2
`

type DeleteSavedPostParams struct {
	PostID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteSavedPost(ctx context.Context, arg DeleteSavedPostParams) error {
	_, err := q.db.ExecContext(ctx, deleteSavedPost, arg.PostID, arg.UserID)
	return err
}

const saveSavedPost = `-- name: SaveSavedPost :exec
INSERT INTO post_saves (id, post_id, user_id) VALUES ($1, $2, $3)
`

type SaveSavedPostParams struct {
	ID     uuid.UUID
	PostID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) SaveSavedPost(ctx context.Context, arg SaveSavedPostParams) error {
	_, err := q.db.ExecContext(ctx, saveSavedPost, arg.ID, arg.PostID, arg.UserID)
	return err
}
