// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: saved_posts.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const savePost = `-- name: SavePost :exec
INSERT INTO post_saves (id, post_id, user_id) VALUES ($1, $2, $3)
`

type SavePostParams struct {
	ID     uuid.UUID
	PostID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) SavePost(ctx context.Context, arg SavePostParams) error {
	_, err := q.db.ExecContext(ctx, savePost, arg.ID, arg.PostID, arg.UserID)
	return err
}

const unsavePost = `-- name: UnsavePost :exec
DELETE FROM post_saves WHERE post_id = $1 AND user_id = $2
`

type UnsavePostParams struct {
	PostID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) UnsavePost(ctx context.Context, arg UnsavePostParams) error {
	_, err := q.db.ExecContext(ctx, unsavePost, arg.PostID, arg.UserID)
	return err
}
