services:
  gator:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GO_VERSION: 1.24.2
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    environment:
      - DATABASE_PATH=/data/gator.db
    command: sh -c "make migrate-up && ./main"
    restart: unless-stopped 