name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: make test
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
      - name: Get machine ID
        run: |
          for i in {1..3}; do
            MACHINE_ID=$(flyctl machines list --json | jq -r '.[0].id')
            if [ "$MACHINE_ID" != "null" ] && [ -n "$MACHINE_ID" ]; then
              echo "MACHINE_ID=$MACHINE_ID" >> $GITHUB_ENV
              break
            fi
            sleep 5 
          done
          
          if [ -z "$MACHINE_ID" ] || [ "$MACHINE_ID" = "null" ]; then
            echo "Failed to get machine ID after 3 attempts"
            exit 1
          fi
      - name: Run migrations
        run: |
          flyctl console --machine "$MACHINE_ID" --command "DATABASE_PATH=/data/gator.db make migrate-up"
