name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: make test
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
      - name: Get machine ID
        run: |
          MACHINE_ID=$(flyctl machines list --json | jq -r '.[0].id')
          if [ "$MACHINE_ID" != "null" ] && [ -n "$MACHINE_ID" ]; then
            echo "MACHINE_ID=$MACHINE_ID" >> $GITHUB_ENV
          else
            echo "Failed to get machine ID"
            exit 1
          fi
      - name: Start machine
        run: |
          echo "Starting machine $MACHINE_ID..."
          flyctl machines start "$MACHINE_ID"
      - name: Run migrations
        env:
          DATABASE_PATH: /data/gator.db
        run: |
          flyctl console --machine "$MACHINE_ID" --command "make migrate-up"
