name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: make test
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
      - name: Get machine ID
        run: |
          MACHINE_ID=$(flyctl machines list --json | jq -r '.[0].id')
          if [ "$MACHINE_ID" = "null" ] || [ -z "$MACHINE_ID" ]; then
            echo "Machine not ready yet"
            exit 1
          fi
          echo "MACHINE_ID=$MACHINE_ID" >> $GITHUB_ENV
        retries: 3
        retry-on: failure
      - name: Run migrations
        run: |
          flyctl console --machine "$MACHINE_ID" --command "DATABASE_PATH=/data/gator.db make migrate-up"
